### ISSUE TITLE
AutoML Mode Question

### ISSUE THREAD

**Issue by impulsecorp** [carefree0910/carefree-learn#26]
Maybe I am misunderstanding how it works, but when I run your latest version in automl mode (using https://github.com/carefree0910/carefree-learn/blob/dev/examples/titanic/automl.py), it runs the same methods it always did (fcnn_optuna, tree_dnn_optuna, etc.) and gets the same Kaggle score as before (0.78947). But in your latest version you wrote that you 
"Implemented more models (Linear, TreeLinear, Wide and Deep, RNN, Transformer, etc.).". Shouldn't those be in the automl part?

**Comment by carefree0910** [comment]
The latest release note wrote the differences between the current version and the previous one (the `v0.1.2`, which released a few months ago), so you've actually experienced most of the new features in `cflearn.Auto`.

In other words, there may be nothing new for you because you catched up with `carefree-learn`'s update frequently 😄

> BTW these new models have actually added to `cflearn.Auto` (except the `TreeLinear` and the `Wide and Deep` because they are not well tested yet), [this piece of code](https://github.com/carefree0910/carefree-learn/blob/ff8eb81bb8f7d9a1c3d783cbbf0b0997863e1cc5/cflearn/api/auto.py#L71-L79) could demonstrate this 😉
> And you can actually customize what models `cflearn.Auto` will search for, by specifying the `models` kwarg [here](https://github.com/carefree0910/carefree-learn/blob/ff8eb81bb8f7d9a1c3d783cbbf0b0997863e1cc5/cflearn/api/auto.py#L48) 😆

**Comment by impulsecorp** [comment]
Ok, thanks.
