### ISSUE TITLE
Split?

### ISSUE THREAD

**Issue by jmrichardson** [carefree0910/carefree-learn#6]
Hi,  I am new to carefree and enjoying it so far.  I am using cv_split=.2.  My data is not IID and temporal so want to make sure the split is doesn't shuffle/stratify.  It appears from your code that it does not shuffle:

`split = self.tr_data.split(self._cv_split)`

Is this correct?

**Comment by carefree0910** [comment]
Hi, I'm very happy that you enjoy `carefree-learn`! But unfortunately, this line of code:

```python
split = self.tr_data.split(self._cv_split)
```

Which comes from [`carefree-data`](https://github.com/carefree0910/carefree-data), does shuffle in most of the time 😢

But don't worry, since this is a reasonable feature request, I'll try to add an argument called `shuffle` in `self.tr_data.split` ASAP so you can decide it yourself! 😉

**Comment by carefree0910** [comment]
BTW The reason why `self.tr_data.split` shuffles the data is that [`carefree-data`](https://github.com/carefree0910/carefree-data) will try to make sure that the split data has the same label distribution as the original data. This is extremely helpful when we are splitting an imbalanced data.

**Comment by jmrichardson** [comment]
That is awesome, thank you for the feature addition.  Unfortunately in my case, splitting with distribution balance is problematic because of the temporal nature of the data.

**Comment by carefree0910** [comment]
Hi @jmrichardson , now we can split the data with different orders like this:

```python
split = self.tr_data.split(self._cv_split, order=xxx)
```

For now, `xxx` could be `"auto"`, `"bottom_up"` or `"top_down"` 😉
