### ISSUE TITLE
Managing CUDA memory?

### ISSUE THREAD

**Issue by Data-drone** [carefree0910/carefree-learn#61]
I was trying this on a kaggle dataset and ran into CUDA Out of Memory issues.

How can I adjust the `Auto` and `fit` functions to make sure that this doesn't happen?

**Comment by carefree0910** [comment]
Yes! There are two ways to adjust:
+ specify target model in `Auto` to reduce the scale of the experiment:
```python
auto = cflearn.Auto(..., models="fcnn")
```
The CUDA out of memory issue may be caused by searching the `tree_dnn` parameters, and I'm planning to reduce it soon 😉
+ specify `cuda="cpu"` in `fit` to use CPU instead of CUDA:
```python
auto.fit(..., cuda="cpu")
```
However this may slow down the whole process 🤣
