### ISSUE TITLE
example of how to use `Element`?

### ISSUE THREAD

**Issue by Data-drone** [carefree0910/carefree-learn#62]
Can you include an example in the docs of how to use Elements?

I don't understand how to the config management fits into `Auto` and `fit` or am I not supposed to use a custom config with Auto?

is the `Elements` just the internal structure that you use to store a config json or am I supposed to create an Elements object then update values in that?

**Comment by carefree0910** [comment]
I should admit that I haven't made this part clear enough in the doc, and I'll try to clarify it ASAP 🤣

The conclusions are:
+ We can specify `extra_config` in `fit` to add the configurations:
```python
auto.fit(..., extra_config={...})
```
And the usage of `extra_config` should be equivalent to the usage of `config` in [`make`](https://carefree0910.me/carefree-learn-doc/docs/getting-started/configurations#make) API.

> `extra_config` is not able to overwrite the hyperparameters generated by the search space (e.g., the `optimizer`), so in fact the options we can play with it are limited 🤣
> 
> And [here](https://carefree0910.me/carefree-learn-doc/docs/user-guides/auto-ml/#define-search-spaces) is the documentation on how to define the search spaces 😄

+ Yes, `Elements` is more of an internal structure than an external API, but you can also use it directly. As shown in [this](https://carefree0910.me/carefree-learn-doc/docs/getting-started/configurations#make) section:
> The reason why we introduce the `make` API is that we hope we can provide APIs as *carefree* as possible. So we've listed the most commonly used configurations in `Elements`, and supported users to specify them through `kwargs` (which is the most intuitive way) in `make`.

I've also provided an example there:
```python
import cflearn

m = cflearn.make(cuda="cpu")
print(m.device)  # cpu
```
And the equivalent `Elements` usage is:
```python
from cflearn.configs import *
from cflearn.pipeline import Pipeline

elements = Elements(cuda="cpu", user_config={}, user_increment_config={})
environment = Environment.from_elements(elements)
m = Pipeline(environment)
print(m.device)  # cpu
```
The `user_config={}, user_increment_config={}` part is caused by a legacy bug, in the future (`v0.1.9`), it should be simplified as:
```python
elements = Elements(cuda="cpu")
```

---

If problems still remain, feel free to comment here anytime! 😄

**Comment by carefree0910** [comment]
+ I've made a small piece of notification [here](https://carefree0910.me/carefree-learn-doc/docs/getting-started/configurations/#high-level-apis).
+ And included an example [here](https://carefree0910.me/carefree-learn-doc/docs/getting-started/configurations/#example).
> This example is valid only if we've reached `v0.1.9`, though. Before that, we have to specify the `user_config` and `user_increment_config` manually, as mentioned above.

Hope they help!

**Comment by carefree0910** [comment]
Documentation on [Define Search Spaces](https://carefree0910.me/carefree-learn-doc/docs/user-guides/auto-ml/#define-search-spaces) has been updated!
